### ISSUE TITLE
Tickbox spacing

### ISSUE THREAD

**Issue by michelleblood** [wfp/editorial-guide#20]
The spacing between the tickbox and the text needs to be increased. On the print version it appears fine.

It can be seen on http://cdn.wfp.org/guides/editorial/content/sentences/

![image](https://cloud.githubusercontent.com/assets/16347974/11893982/9d99eabe-a574-11e5-9b42-e069a9994635.png)

**Comment by jrah** [comment]
I think this is possibly created because the tick is wider than the X mark. My solution would be to conform better to the latest WFP UI Guide (see screenshot). 
![screenshot 2016-02-01 15 33 07](https://cloud.githubusercontent.com/assets/1245961/12721771/4d85af88-c8f9-11e5-81c4-9e4cfcdfd4f3.png)

This will involve altering all the blockquotes with the relevant headings. Please tell me if you need different headings.

**Comment by matthewmorek** [comment]
Let's use UI icons from [WFP UI](http://cdn.wfp.org/guides/ui/v0.5.0/resources/ui-icons/), instead of Unicode characters; they will always look the same, regardless of the font used.

**Comment by jrah** [comment]
@matthewmorek @michelleblood @zwollo 

Here is a mockup with the the UI icons:
<img width="749" alt="screenshot 2016-02-02 14 22 07" src="https://cloud.githubusercontent.com/assets/1245961/12752053/783a657e-c9b8-11e5-90fb-be4dc93fa97d.png">

The tick is naturally wider than the X mark but the text lines up.

**Comment by matthewmorek** [comment]
That should solve the issue, as fast as I can tell. @zwollo?

**Comment by zwollo** [comment]
If it also displays well on the print version, please proceed.
